/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example;

import org.testng.annotations.*;

public class InstallDeviceTest {
    @BeforeClass
    public void setupTestClass() {
        System.out.println("setupTestClass");
    }

    @BeforeMethod
    public void setupTestMethod() {
        System.out.println("setupTestMethod");
    }

    @Test
    public void installDeviceTest() {
        System.out.println("Test method");
    }

    @AfterClass
    public void teardownTestClass() {
        System.out.println("teardownTestClass");
    }

    @AfterMethod
    public void teardownTestMethod() {
        System.out.println("teardownTestMethod");
    }
}
